#!/usr/bin/env bash
# Configure RaspAP-backed guest WiFi AP + usb0 WAN uplink.
#   wlan0 / AP_SSID (default AUTOPI) — guest (QR), subnet 10.3.141.0/24
# Admin access: USB gadget (onboard WiFi supports only one AP).
set -euo pipefail

AP_ENV="/etc/autopi/ap.env"
HOSTAPD_CONF="/etc/hostapd/hostapd.conf"
HOSTAPD_BACKUP="/etc/hostapd/hostapd.conf.autopi.bak"
DNSMASQ_GUEST="/etc/dnsmasq.d/090_autopi_guest.conf"
DNSMASQ_ADMIN="/etc/dnsmasq.d/091_autopi_admin.conf"
WLAN_ADDR_SCRIPT="/usr/local/sbin/autopi-wlan-addrs.sh"
WLAN_ADDR_SERVICE="/etc/systemd/system/autopi-wlan-addrs.service"

GUEST_GATEWAY="10.3.141.1"
ADMIN_GATEWAY="10.3.142.1"
GUEST_SUBNET="10.3.141.0/24"
ADMIN_SUBNET="10.3.142.0/24"
ADMIN_SSID="${ADMIN_SSID:-autopi-admin}"

rand_psk() {
  local n="${1:-12}"
  openssl rand -base64 32 | tr -d '/+=' | head -c "${n}"
}

sudo mkdir -p /etc/autopi

# Capture laptop .env overrides before sourcing on-Pi ap.env (source would clobber them).
AP_SSID_OVERRIDE="${AP_SSID:-}"
AP_HOSTNAME_OVERRIDE="${AP_HOSTNAME:-}"

if [[ -f "${AP_ENV}" ]]; then
  if [[ -r "${AP_ENV}" ]]; then
    # shellcheck source=/dev/null
    source "${AP_ENV}"
  else
    # shellcheck source=/dev/null
    source <(sudo cat "${AP_ENV}")
  fi
  echo "Reusing existing AP credentials from ${AP_ENV}"
else
  GUEST_PSK="$(rand_psk 12)"
  ADMIN_PSK="$(rand_psk 16)"
fi

# Laptop .env wins for SSID / DNS name when provided.
GUEST_SSID="${AP_SSID_OVERRIDE:-${GUEST_SSID:-AUTOPI}}"
AP_HOSTNAME="${AP_HOSTNAME_OVERRIDE:-${AP_HOSTNAME:-autopi.lan}}"
AP_HOSTNAME="$(echo "${AP_HOSTNAME}" | tr '[:upper:]' '[:lower:]')"
# Allow single-label or dotted names (prefer *.lan for phones).
if [[ ! "${AP_HOSTNAME}" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$|^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$ ]]; then
  echo "Error: invalid AP_HOSTNAME='${AP_HOSTNAME}'" >&2
  exit 1
fi

: "${GUEST_PSK:?}"
: "${ADMIN_PSK:?}"

sudo tee "${AP_ENV}" > /dev/null <<EOF
# Generated by configure_raspap_guest_ap.sh — do not commit
AP_SSID=${GUEST_SSID}
AP_HOSTNAME=${AP_HOSTNAME}
GUEST_SSID=${GUEST_SSID}
GUEST_PSK=${GUEST_PSK}
GUEST_GATEWAY=${GUEST_GATEWAY}
GUEST_SUBNET=${GUEST_SUBNET}
GUEST_DASHBOARD_URL=http://${AP_HOSTNAME}:8080/
ADMIN_SSID=${ADMIN_SSID}
ADMIN_PSK=${ADMIN_PSK}
ADMIN_GATEWAY=${ADMIN_GATEWAY}
ADMIN_SUBNET=${ADMIN_SUBNET}
WAN_IFACE=usb0
EOF
# Readable by the installing user/group so setup scripts + autopi-web can load it.
sudo chown "root:$(id -gn)" "${AP_ENV}"
# World-readable SSID/PSK for guest QR is intentional; admin PSK is also in this file —
# keep group-readable for the dashboard user, and readable by autopi-web.
sudo chmod 640 "${AP_ENV}"
# Ensure the installing user can always read it (systemd runs as that user).
if ! sudo -u "$(id -un)" test -r "${AP_ENV}"; then
  sudo chmod 644 "${AP_ENV}"
  echo "  Note: ${AP_ENV} set to 644 so the dashboard can read guest QR credentials"
fi
echo "Wrote ${AP_ENV}"

# ── Free wlan0 from NetworkManager (cannot be station + AP) ───────────────────
NM_UNMANAGED="/etc/NetworkManager/conf.d/99-autopi-wlan-ap.conf"
echo "Taking wlan0 out of NetworkManager client mode for hostapd..."
sudo tee "${NM_UNMANAGED}" > /dev/null <<'EOF'
# autopi — wlan0 is a hostapd AP, not an NM station
[keyfile]
unmanaged-devices=interface-name:wlan0
EOF

if command -v nmcli &>/dev/null; then
  # Disable autoconnect on any WiFi client profiles (keep them for emergency use)
  while read -r con; do
    [[ -z "${con}" ]] && continue
    type="$(nmcli -g connection.type connection show "${con}" 2>/dev/null || true)"
    if [[ "${type}" == "802-11-wireless" ]]; then
      mode="$(nmcli -g 802-11-wireless.mode connection show "${con}" 2>/dev/null || true)"
      if [[ "${mode}" != "ap" ]]; then
        echo "  Disabling WiFi client autoconnect: ${con}"
        sudo nmcli connection modify "${con}" connection.autoconnect no || true
        sudo nmcli connection down "${con}" 2>/dev/null || true
      fi
    fi
  done < <(nmcli -t -f NAME connection show)
  sudo nmcli device set wlan0 managed no 2>/dev/null || true
  sudo systemctl reload NetworkManager 2>/dev/null || sudo nmcli general reload conf 2>/dev/null || true
fi

# Drop leftover client addresses so only the AP gateway remains after hostapd starts
sudo ip link del wlan0_1 2>/dev/null || true
sudo ip addr flush dev wlan0 2>/dev/null || true
sudo ip link set wlan0 down 2>/dev/null || true
sudo ip link set wlan0 up 2>/dev/null || true

# ── hostapd single AP ─────────────────────────────────────────────────────────
# Pi onboard WiFi only allows #{ AP } <= 1 — dual BSS (wlan0_1) will not start.
# Guest QR AP on wlan0; admin access is USB gadget (and eth0 if used).
if [[ -f "${HOSTAPD_CONF}" && ! -f "${HOSTAPD_BACKUP}" ]]; then
  sudo cp "${HOSTAPD_CONF}" "${HOSTAPD_BACKUP}"
  echo "Backed up hostapd.conf → ${HOSTAPD_BACKUP}"
fi

sudo tee "${HOSTAPD_CONF}" > /dev/null <<EOF
# autopi guest AP — managed by configure_raspap_guest_ap.sh
# Single SSID only: this radio does not support concurrent dual AP/BSS.
country_code=US
interface=wlan0
driver=nl80211
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0

ssid=${GUEST_SSID}
wpa=2
wpa_passphrase=${GUEST_PSK}
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
EOF
echo "Wrote single-AP ${HOSTAPD_CONF} (SSID=${GUEST_SSID})"

# ── Interface address after hostapd starts ────────────────────────────────────
sudo tee "${WLAN_ADDR_SCRIPT}" > /dev/null <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
for i in $(seq 1 30); do
  ip link show wlan0 &>/dev/null && break
  sleep 1
done
ip addr replace 10.3.141.1/24 dev wlan0
ip link set wlan0 up

# Prefer usb0 as default route when it has a gateway (Mac sharing).
if ip link show usb0 &>/dev/null; then
  ip link set usb0 up || true
fi

# dnsmasq must re-bind after wlan0 has 10.3.141.1 (otherwise DNS listens only on lo).
if systemctl cat dnsmasq.service &>/dev/null; then
  systemctl try-restart dnsmasq.service || true
fi
EOF
sudo chmod +x "${WLAN_ADDR_SCRIPT}"

# ── usb0 must be a CLIENT of the Mac, not a shared gateway ────────────────────
# If NM has "USB Gadget (shared)", the Pi becomes 10.12.194.1 and the Mac's
# default route can point at the Pi — breaking Mac internet when plugged in.
#
# Never nmcli down/up usb0 while this SSH session is itself on usb0 — that
# wedges the TCP session so even `timeout` never returns to the laptop.
ssh_via_usb0() {
  [[ -n "${SSH_CONNECTION:-}" ]] || return 1
  local server_ip
  server_ip="$(awk '{print $3}' <<<"${SSH_CONNECTION}")"
  [[ -n "${server_ip}" ]] || return 1
  ip -4 -o addr show usb0 2>/dev/null | grep -q " ${server_ip}/"
}

echo "Configuring usb0 as DHCP client (Mac provides uplink; Pi must not share)..."
if command -v nmcli &>/dev/null; then
  USB_LIVE_CHANGES=1
  if ssh_via_usb0; then
    USB_LIVE_CHANGES=0
    echo "  SSH is on usb0 — will only save profiles (no down/up; avoids freezing this session)"
  fi

  # Tear down any shared profiles on usb0 (skip live down/delete if SSH rides usb0)
  while read -r con; do
    [[ -z "${con}" ]] && continue
    method="$(nmcli -g ipv4.method connection show "${con}" 2>/dev/null || true)"
    if [[ "${method}" == "shared" ]]; then
      echo "  Found shared connection: ${con}"
      if [[ "${USB_LIVE_CHANGES}" -eq 1 ]]; then
        sudo nmcli connection down "${con}" 2>/dev/null || true
        sudo nmcli connection delete "${con}" 2>/dev/null || true
      else
        sudo nmcli connection modify "${con}" \
          connection.autoconnect no \
          ipv4.method auto \
          ipv4.may-fail yes \
          connection.id 'USB Gadget (client)' \
          || true
        echo "  Converted shared → client profile (takes effect after USB replug or reboot)"
      fi
    fi
  done < <(nmcli -t -f NAME,DEVICE connection show | awk -F: '$2=="usb0" {print $1}')

  if nmcli -t -f NAME connection show | grep -qx 'USB Gadget (shared)'; then
    if [[ "${USB_LIVE_CHANGES}" -eq 1 ]]; then
      echo "  Removing connection 'USB Gadget (shared)'"
      sudo nmcli connection delete 'USB Gadget (shared)' 2>/dev/null || true
    else
      sudo nmcli connection modify 'USB Gadget (shared)' connection.autoconnect no || true
    fi
  fi

  if nmcli -t -f NAME connection show | grep -qx 'USB Gadget (client)'; then
    echo "  Ensuring profile 'USB Gadget (client)' (DHCP from Mac)"
    sudo nmcli connection modify 'USB Gadget (client)' \
      connection.interface-name usb0 \
      connection.autoconnect yes \
      ipv4.method auto \
      ipv4.may-fail yes \
      ipv4.never-default no \
      ipv6.method auto \
      ipv6.may-fail yes \
      ipv6.never-default yes
  else
    echo "  Creating 'USB Gadget (client)' (DHCP from Mac)"
    sudo nmcli connection add type ethernet ifname usb0 con-name 'USB Gadget (client)' \
      ipv4.method auto \
      ipv4.may-fail yes \
      ipv6.method auto \
      ipv6.may-fail yes \
      ipv6.never-default yes \
      connection.autoconnect yes
  fi

  # Never activate usb0 here. `nmcli connection up` renegotiates the link; if this
  # SSH session (or mDNS) rides usb0, the session freezes and even `timeout` never
  # returns to the laptop. Autoconnect applies on reboot / cable replug.
  echo "  Skipping usb0 activation (avoids freezing SSH). Replug USB or reboot to apply."
else
  echo "  nmcli not available; ensure usb0 is not running a DHCP server toward the Mac."
fi

sudo tee "${WLAN_ADDR_SERVICE}" > /dev/null <<EOF
[Unit]
Description=autopi WiFi AP interface addresses
After=hostapd.service
Wants=hostapd.service

[Service]
Type=oneshot
ExecStart=${WLAN_ADDR_SCRIPT}
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

# ── dnsmasq DHCP pool (guest AP only) ─────────────────────────────────────────
sudo tee "${DNSMASQ_GUEST}" > /dev/null <<EOF
# Guest AP — GUI only clients
# bind-dynamic: pick up 10.3.141.1 after hostapd/addrs (bind-interfaces misses it)
interface=wlan0
bind-dynamic
listen-address=${GUEST_GATEWAY}
listen-address=127.0.0.1
# Do not answer from /etc/hosts (hostnamectl puts ${AP_HOSTNAME} on 127.0.1.1)
no-hosts
dhcp-range=set:guest,10.3.141.50,10.3.141.150,255.255.255.0,12h
dhcp-option=tag:guest,3,${GUEST_GATEWAY}
# Force guest DNS to this AP so AP_HOSTNAME resolves (not public 1.1.1.1)
dhcp-option=tag:guest,6,${GUEST_GATEWAY}
dhcp-option=option:dns-server,${GUEST_GATEWAY}
# Readable dashboard name for phones on this AP (dotted name — iOS dislikes single-label)
address=/${AP_HOSTNAME}/${GUEST_GATEWAY}
host-record=${AP_HOSTNAME},${GUEST_GATEWAY}
# Also map short "autopi" if AP_HOSTNAME is autopi.lan
address=/autopi/${GUEST_GATEWAY}
domain=lan
local=/lan/
# Captive-portal assist
address=/captive.apple.com/${GUEST_GATEWAY}
address=/connectivitycheck.gstatic.com/${GUEST_GATEWAY}
address=/www.msftconnecttest.com/${GUEST_GATEWAY}
EOF

# Remove legacy admin AP dnsmasq if present (dual-BSS not supported on this radio)
sudo rm -f "${DNSMASQ_ADMIN}"

# RaspAP ships a second wlan0 DHCP config that conflicts (public DNS, duplicate ranges).
for f in /etc/dnsmasq.d/090_wlan0.conf /etc/dnsmasq.d/090_wlan0.conf.bak; do
  if [[ -f "${f}" ]]; then
    sudo mv -f "${f}" "${f}.dpkg-old"
    echo "  Disabled conflicting ${f}"
  fi
done
if [[ -f /etc/dnsmasq.d/090_raspap.conf ]] && grep -q '^conf-dir=' /etc/dnsmasq.d/090_raspap.conf; then
  sudo sed -i 's/^conf-dir=/# conf-dir=/' /etc/dnsmasq.d/090_raspap.conf || true
fi

# Enable IP forwarding (kept for future USB NAT / extra radios)
if ! grep -q '^net.ipv4.ip_forward=1' /etc/sysctl.d/99-autopi-ap.conf 2>/dev/null; then
  echo 'net.ipv4.ip_forward=1' | sudo tee /etc/sysctl.d/99-autopi-ap.conf > /dev/null
  sudo sysctl -p /etc/sysctl.d/99-autopi-ap.conf
fi

# RaspAP lighttpd binds :80 on all interfaces and steals http://autopi.lan/ from phones.
# Keep RaspAP UI on loopback only (USB/SSH tunnel); guest traffic uses :8080.
if [[ -f /etc/lighttpd/lighttpd.conf ]]; then
  if ! grep -q 'autopi-bind-loopback' /etc/lighttpd/lighttpd.conf; then
    echo "Restricting lighttpd to 127.0.0.1 (free :80 on wlan0 for captive redirect)..."
    sudo cp /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.autopi.bak
    sudo sed -i 's/^server.bind.*/# &/' /etc/lighttpd/lighttpd.conf || true
    sudo sed -i 's|^include_shell "/usr/share/lighttpd/use-ipv6.pl|# &|' /etc/lighttpd/lighttpd.conf || true
    sudo tee -a /etc/lighttpd/lighttpd.conf > /dev/null <<'EOF'

# autopi-bind-loopback — guest AP needs :80 for captive-portal redirect to :8080
server.bind = "127.0.0.1"
EOF
  fi
  # Ensure IPv6 wildcard :80 is not left enabled from earlier installs
  sudo sed -i 's|^include_shell "/usr/share/lighttpd/use-ipv6.pl|# &|' /etc/lighttpd/lighttpd.conf || true
  sudo systemctl restart lighttpd 2>/dev/null || true
fi

# Ensure hostapd is unmasked/enabled (RaspAP usually does this)
sudo systemctl unmask hostapd 2>/dev/null || true
sudo systemctl enable hostapd
sudo systemctl enable "${WLAN_ADDR_SERVICE##*/}"
sudo systemctl daemon-reload

sudo systemctl reset-failed hostapd.service 2>/dev/null || true
if sudo systemctl restart hostapd.service; then
  echo "hostapd: started"
else
  echo "hostapd: FAILED to start — see: journalctl -u hostapd -n 40" >&2
  journalctl -u hostapd -n 20 --no-pager >&2 || true
fi
sudo systemctl start autopi-wlan-addrs.service || true
# hostapd restart can briefly drop 10.3.141.1 — wait until it's back before DNS bind
for _ in $(seq 1 20); do
  ip -4 addr show wlan0 | grep -q '10.3.141.1/24' && break
  sleep 0.5
done

# Ensure dnsmasq starts *after* wlan0 has 10.3.141.1
if systemctl cat dnsmasq.service &>/dev/null; then
  sudo mkdir -p /etc/systemd/system/dnsmasq.service.d
  sudo tee /etc/systemd/system/dnsmasq.service.d/autopi.conf > /dev/null <<EOF
[Unit]
After=autopi-wlan-addrs.service hostapd.service
Wants=autopi-wlan-addrs.service
EOF
  sudo systemctl daemon-reload
  sudo systemctl enable dnsmasq
  sudo systemctl reset-failed dnsmasq.service 2>/dev/null || true
  if sudo systemctl restart dnsmasq.service; then
    echo "dnsmasq: started (guest DHCP/DNS ${GUEST_GATEWAY}, name ${AP_HOSTNAME})"
  else
    echo "dnsmasq: FAILED — phones will not get an IP / cannot resolve ${AP_HOSTNAME}" >&2
    journalctl -u dnsmasq -n 20 --no-pager >&2 || true
  fi
else
  echo "dnsmasq: service not installed" >&2
fi

echo ""
echo "Guest AP configured:"
echo "  Guest  SSID=${GUEST_SSID}  gateway=${GUEST_GATEWAY}  (QR / GUI-only)"
echo "  URL    http://${AP_HOSTNAME}:8080/  (DNS on guest AP; :80→8080 for captive probes)"
echo "  Admin  use USB gadget (Pi onboard WiFi supports only one AP — no autopi-admin SSID)"
echo "  WAN    usb0 as DHCP client (Mac → Pi uplink; do NOT use Pi shared mode)"
echo "Credentials: ${AP_ENV}"
echo ""
echo "On the Mac:"
echo "  1. System Settings → Sharing → Internet Sharing: share Wi‑Fi → USB gadget (optional, for Pi internet)"
echo "  2. Or leave USB as link-local for SSH only — keep Wi‑Fi above USB in network service order"
echo "NOTE: If you change Hotspot settings in the RaspAP web UI, re-run this script."
